### ISSUE TITLE
tweets-loader.min.js is not work.

### ISSUE THREAD

**Issue by basictomonokai** [lf2com/tweets-loader.js#1]
What happen?

tweets-loader.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'getAttribute' of null
    at tweets-loader.min.js:1
    at NodeList.map (<anonymous>)
    at o (tweets-loader.min.js:1)
    at tweets-loader.min.js:1

**Comment by lf2com** [comment]
Hi @basictomonokai,
This issue comes out because tweets-loader couldn't find the tweet's author icon. I'll fixed it later. Since there is no author icon to catch, the result would probabily be without author thumbnails. I'll try to find out other ways to load tweets if possible.

Also, I found that Twitter will have changes on widget settings. The widget settings page would no longer support creating and editing widgets. Here is the detail:
https://twittercommunity.com/t/deprecating-widget-settings/102295

**Comment by lf2com** [comment]
I just fixed the [bug](https://github.com/lf2com/tweets-loader.js/commit/4ddd70632bf2e3716906a229bc896b316302f2d5). And I'll look for another reliable way to grab tweets.

**Comment by basictomonokai** [comment]
I tested fixed version and result is OK.  Thanks you.

> And I'll look for another reliable way to grab tweets.

I use your JS for my own widget dashboard.

![clipboard02zzz](https://user-images.githubusercontent.com/7356905/38070353-8f31ae22-3356-11e8-8d21-eee299fbe60a.jpg)

Your JS is very useful.

But "Deprecating widget settings" ... I'm sad.

**Comment by lf2com** [comment]
Glad to see that you use tweets-loader!
If there is any good news I'll apply it to this repository.
